import { useEffect, useMemo } from "react"
import { Download, Sparkles } from "lucide-react"

import { useVerificationStore } from "@/lib/verification-store"

const baseCards = [
  {
    icon: "💊",
    title: "Your Product",
    dosage: "2 capsules daily",
    timing: "Morning with water",
    note: "Consistency is key for best results",
  },
  {
    icon: "🧪",
    title: "Stack Suggestion",
    dosage: "As directed",
    timing: "With meals",
    note: "Pair recommendations from API",
  },
  {
    icon: "🏋️",
    title: "Recovery Support",
    dosage: "1 serving",
    timing: "Post workout",
    note: "From product metadata",
  },
]
const delayClasses = ["[transition-delay:0ms]", "[transition-delay:120ms]", "[transition-delay:240ms]"]

function CoachSection() {
  const { productData } = useVerificationStore()
  const productName = productData?.product?.name || "Your Product"

  const cards = useMemo(
    () => [
      { ...baseCards[0], title: productName },
      ...baseCards.slice(1),
    ],
    [productName],
  )

  useEffect(() => {
    const elements = document.querySelectorAll(".coach-card")
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.remove("opacity-0", "translate-y-8")
            entry.target.classList.add("opacity-100", "translate-y-0")
            observer.unobserve(entry.target)
          }
        })
      },
      { threshold: 0.2 },
    )
    elements.forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [])

  const handleDownloadPlan = () => {
    const planContent = [
      "SPUNGE EXPERT WELLNESS PLAN",
      "----------------------------------------",
      "Expert currated plan from Spunge to the user.",
      "",
      `Product: ${productName}`,
      "",
      ...cards.flatMap((card, index) => [
        `${index + 1}. ${card.title}`,
        `   Dosage: ${card.dosage}`,
        `   Best time: ${card.timing}`,
        `   Expert note: ${card.note}`,
        "",
      ]),
      "Generated by Spunge verification experience.",
    ].join("\n")

    const blob = new Blob([planContent], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = url
    link.download = `spunge-expert-plan-${new Date().toISOString().slice(0, 10)}.txt`
    document.body.appendChild(link)
    link.click()
    link.remove()
    URL.revokeObjectURL(url)
  }

  return (
    <section id="coach" className="bg-shift overflow-hidden rounded-2xl bg-[linear-gradient(120deg,#edf8f6,#f8fcfb,#edf8f6)] py-10 sm:py-14 lg:py-16">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mb-7 flex flex-col gap-4 sm:mb-8 lg:mb-10 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="text-[11px] uppercase tracking-[0.24em] text-[var(--green)] sm:text-sm">Guided by experts</p>
            <h2 className="mt-2 text-2xl font-bold leading-tight sm:mt-3 sm:text-4xl">Your Expert Wellness Plan</h2>
            <p className="mt-2 text-sm text-[var(--muted)] sm:mt-3 sm:text-base">
              Curated specifically for {productName}.
            </p>
            <p className="mt-3 text-xs font-medium text-[#3a6966] sm:text-sm">
              Expert currated plan from Spunge to the user.
            </p>
            <button
              type="button"
              onClick={handleDownloadPlan}
              className="group mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[linear-gradient(135deg,#11b5b2,#3ebf6a)] px-4 py-2.5 text-sm font-semibold text-white shadow-[0_8px_24px_rgba(17,181,178,0.28)] transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_14px_32px_rgba(17,181,178,0.35)] focus:outline-none focus:ring-2 focus:ring-[#11b5b2]/50 sm:w-auto sm:px-5"
            >
              <Download size={16} className="transition-transform duration-300 group-hover:translate-y-[1px]" />
              <span>Download Expert Plan</span>
              <Sparkles size={15} className="opacity-80 transition-transform duration-300 group-hover:rotate-12" />
            </button>
          </div>

          <div className="flex items-center justify-start gap-3 sm:justify-end sm:gap-4">
            <svg viewBox="0 0 120 120" className="spin-slow h-20 w-20 text-[var(--green)] sm:h-24 sm:w-24">
              <defs>
                <path id="circlePath" d="M60,60 m-44,0 a44,44 0 1,1 88,0 a44,44 0 1,1 -88,0" />
              </defs>
              <text className="fill-current text-[12px] tracking-[0.18em]">
                <textPath href="#circlePath">EXPERT CURATED • EXPERT CURATED •</textPath>
              </text>
            </svg>
          </div>
        </div>

        <div className="grid gap-3 sm:gap-4 md:grid-cols-2 lg:grid-cols-3">
          {cards.map((card, index) => (
            <article
              key={card.title}
              className={`coach-card relative rounded-2xl border border-[var(--border)] bg-white p-4 opacity-0 translate-y-8 transition duration-700 hover:-translate-y-1 hover:border-[var(--green)]/50 hover:shadow-[0_8px_24px_var(--green-glow)] sm:p-5 lg:p-6 ${delayClasses[index]}`}
            >
              <div className="pointer-events-none absolute right-3 top-3 h-8 w-8 rounded-full bg-[radial-gradient(circle,rgba(17,181,178,0.18),rgba(17,181,178,0))]" />
              <div className="mb-2 text-2xl sm:mb-3 sm:text-3xl">{card.icon}</div>
              <h3 className="text-lg font-semibold sm:text-xl">
                {card.title}
              </h3>
              <div className="mt-3 space-y-1.5 text-sm text-[var(--muted)] sm:mt-4 sm:space-y-2">
                <p>Dosage: {card.dosage}</p>
                <p>Best time: {card.timing}</p>
                <p>Expert note: {card.note}</p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  )
}

export default CoachSection
